title: rifkifau
description: Personal Blog Rifki Fauzi / WebGIS Enthusiast Yogyakarta Indonesia / Kumpulan Proses Belajar

url: https://rifkifau.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: rifkifau
   twitter: rifkifau
   facebook: irifkifau
   email: rifkifau@gmail.com
   linkedin: rifki-fauzi
   youtube: UCTiE-IYGCZehFW43Vo7r03A
   googleplus: MariSpasialkan

google_analytics: "UA-58263416-1"
